from ROOT import *
import numpy as n

DEBUG = 0

class GenTools:

   def __init__(self):
       self.totevs = n.zeros(1, dtype=float)
       self.gen1_pt = n.zeros(1, dtype=float)
       self.gen2_pt = n.zeros(1, dtype=float)
       self.gen3_pt = n.zeros(1, dtype=float)
       self.gen4_pt = n.zeros(1, dtype=float)
       self.gen1_eta = n.zeros(1, dtype=float)
       self.gen2_eta = n.zeros(1, dtype=float)
       self.gen3_eta = n.zeros(1, dtype=float)
       self.gen4_eta = n.zeros(1, dtype=float)
       self.gen1_phi = n.zeros(1, dtype=float)
       self.gen2_phi = n.zeros(1, dtype=float)
       self.gen3_phi = n.zeros(1, dtype=float)
       self.gen4_phi = n.zeros(1, dtype=float)
       self.gen1_energy = n.zeros(1, dtype=float)
       self.gen2_energy = n.zeros(1, dtype=float)
       self.gen3_energy = n.zeros(1, dtype=float)
       self.gen4_energy = n.zeros(1, dtype=float)
       self.gen12_mass = n.zeros(1, dtype=float)
       self.gen13_mass = n.zeros(1, dtype=float)
       self.gen14_mass = n.zeros(1, dtype=float)
       self.gen23_mass = n.zeros(1, dtype=float)
       self.gen24_mass = n.zeros(1, dtype=float)
       self.gen34_mass = n.zeros(1, dtype=float)
       self.gen12dr = n.zeros(1, dtype=float)
       self.gen13dr = n.zeros(1, dtype=float)
       self.gen14dr = n.zeros(1, dtype=float)
       self.gen23dr = n.zeros(1, dtype=float)
       self.gen24dr = n.zeros(1, dtype=float)
       self.gen34dr = n.zeros(1, dtype=float)
       self.gen_mindr = n.zeros(1, dtype=float)
       self.gen_maxdr = n.zeros(1, dtype=float)
       self.tp_mass = n.zeros(1, dtype=float)

   def MakeGenTree(self):
       outTree = TTree("geninfo","tot evs")
       SetOwnership(outTree,0)

       outTree.Branch('totevs',self.totevs,'totevs/D')
       outTree.Branch('gen1_pt',self.gen1_pt,'gen1_pt/D')
       outTree.Branch('gen2_pt',self.gen2_pt,'gen2_pt/D')
       outTree.Branch('gen3_pt',self.gen3_pt,'gen3_pt/D')
       outTree.Branch('gen4_pt',self.gen4_pt,'gen4_pt/D')
       outTree.Branch('gen1_eta',self.gen1_eta,'gen1_eta/D')
       outTree.Branch('gen2_eta',self.gen2_eta,'gen2_eta/D')
       outTree.Branch('gen3_eta',self.gen3_eta,'gen3_eta/D')
       outTree.Branch('gen4_eta',self.gen4_eta,'gen4_eta/D')
       outTree.Branch('gen1_phi',self.gen1_phi,'gen1_phi/D')
       outTree.Branch('gen2_phi',self.gen2_phi,'gen2_phi/D')
       outTree.Branch('gen3_phi',self.gen3_phi,'gen3_phi/D')
       outTree.Branch('gen4_phi',self.gen4_phi,'gen4_phi/D')
       outTree.Branch('gen1_energy',self.gen1_energy,'gen1_energy/D')
       outTree.Branch('gen2_energy',self.gen2_energy,'gen2_energy/D')
       outTree.Branch('gen3_energy',self.gen3_energy,'gen3_energy/D')
       outTree.Branch('gen4_energy',self.gen4_energy,'gen4_energy/D')
       outTree.Branch('gen12_mass',self.gen12_mass,'gen12_mass/D')
       outTree.Branch('gen13_mass',self.gen13_mass,'gen13_mass/D')
       outTree.Branch('gen14_mass',self.gen14_mass,'gen14_mass/D')
       outTree.Branch('gen23_mass',self.gen23_mass,'gen23_mass/D')
       outTree.Branch('gen24_mass',self.gen24_mass,'gen24_mass/D')
       outTree.Branch('gen34_mass',self.gen34_mass,'gen34_mass/D')
       outTree.Branch('gen12dr',self.gen12dr,'gen12dr/D')
       outTree.Branch('gen13dr',self.gen13dr,'gen13dr/D')
       outTree.Branch('gen14dr',self.gen14dr,'gen14dr/D')
       outTree.Branch('gen23dr',self.gen23dr,'gen23dr/D')
       outTree.Branch('gen24dr',self.gen24dr,'gen24dr/D')
       outTree.Branch('gen34dr',self.gen34dr,'gen34dr/D')
       outTree.Branch('gen_mindr',self.gen_mindr,'gen_mindr/D')
       outTree.Branch('gen_maxdr',self.gen_maxdr,'gen_maxdr/D')
       outTree.Branch('tp_mass',self.tp_mass,'tp_mass/D')

       return outTree
